service: stabilitywarrants
configValidationMode: off
frameworkVersion: "2 || 3"

provider:
  name: scaleway
  runtime: python3
  scwToken: ${env:AWS_SECRET_ACCESS_KEY}
  scwProject: ${env:AWS_PROJECT_ID}
  env:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  extract-sg:
    handler: functions/extract_sg.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Télécharge les stability warrants de la Société Générale
  extract-uc:
    handler: functions/extract_uc.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Télécharge les stability warrants d'Unicredit
  merge:
    handler: functions/merge.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Fusionne les fichiers CSV
  transform:
    handler: functions/transform.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Transforme le fichier CSV
  csv-to-json:
    handler: functions/csv_to_json.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Transforme le fichier CSV en JSON
  run-all-functions:
    handler: functions/run_all_functions.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Exécute toutes les fonctions de la chaîne
    events:
      - schedule:
          rate: "10 2 * * *"
      - schedule:
          rate: "10 10 * * *"
      - schedule:
          rate: "0 14 * * *"
      - schedule:
          rate: "30 19 * * *"
      - schedule:
          rate: "0 0 * * *"
  pivot-point:
    handler: functions/pivot_point.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Calcul des point pivots du CAC40
    events:
      - schedule:
          rate: "10 0 * * *"

plugins:
  - serverless-scaleway-functions
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy:
      - csv
      - json
      - urllib
      - gzip
      - datetime

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"
    - "!.idea/**"
    - "!*.html"
    - "!*.md"
    - "!*.txt"
    - "!docs/**"
