service: stabilitywarrants
configValidationMode: off
frameworkVersion: '2 || 3'

provider:
  name: scaleway
  runtime: python3
  scwToken: ${env:AWS_SECRET_ACCESS_KEY}
  scwProject: ${env:AWS_PROJECT_ID}
  env:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}


functions:
  sort:
    handler: sort.handle
    events:
      - schedule:
          rate: '21 0 * * 1'
      - schedule:
          rate: '21 0 * * 2'
      - schedule:
          rate: '21 0 * * 3'
      - schedule:
          rate: '21 0 * * 4'
      - schedule:
          rate: '21 0 * * 5'

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'