service: stabilitywarrants
configValidationMode: off
frameworkVersion: '2 || 3'

provider:
  name: scaleway
  runtime: python3
  scwToken: ${env:AWS_SECRET_ACCESS_KEY}
  scwProject: ${env:AWS_PROJECT_ID}
  env:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  extract-sg:
    handler: extract-sg.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Télécharge les stability warrants de la Société Générale
    events:
      - schedule:
          rate: '21 0 * * 1'
      - schedule:
          rate: '21 0 * * 2'
      - schedule:
          rate: '21 0 * * 3'
      - schedule:
          rate: '21 0 * * 4'
      - schedule:
          rate: '21 0 * * 5'
  extract-uc:
    handler: extract-uc.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Télécharge les stability warrants d'Unicredit
    events:
      - schedule:
          rate: '21 0 * * 1'
      - schedule:
          rate: '21 0 * * 2'
      - schedule:
          rate: '21 0 * * 3'
      - schedule:
          rate: '21 0 * * 4'
      - schedule:
          rate: '21 0 * * 5'
  sort:
    handler: sort.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Transforme le fichier CSV
    events:
      - schedule:
          rate: '21 1 * * *'
  csv-to-json:
    handler: csv-to-json.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Transforme le fichier CSV en JSON
    events:
      - schedule:
          rate: '21 2 * * *'
  update-page:
    handler: update-page.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Mise à jour de la page HTML
    events:
      - schedule:
          rate: '21 3 * * *'

plugins:
  - serverless-scaleway-functions
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy:
      - csv
      - json
      - urllib
      - gzip
      - datetime

package:
  patterns:
    - '!node_modules/**'
    - '!.gitignore'
    - '!.git/**'