service: stabilitywarrants
configValidationMode: off
frameworkVersion: "2 || 3"

provider:
  name: scaleway
  runtime: python3
  scwToken: ${env:AWS_SECRET_ACCESS_KEY}
  scwProject: ${env:AWS_PROJECT_ID}
  env:
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}

functions:
  extract-sg:
    handler: functions/extract_sg.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Télécharge les stability warrants de la Société Générale
    events:
      - schedule:
          rate: "10 0 * * *"
  extract-uc:
    handler: functions/extract_uc.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Télécharge les stability warrants d'Unicredit
    events:
      - schedule:
          rate: "10 0 * * *"
  merge:
    handler: functions/merge.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Fusionne les fichiers CSV
    events:
      - schedule:
          rate: "12 0 * * *"
  transform:
    handler: functions/transform.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Transforme le fichier CSV
    events:
      - schedule:
          rate: "13 0 * * *"
  csv-to-json:
    handler: functions/csv_to_json.handle
    minScale: 0
    maxScale: 1
    memorySize: 128
    description: Transforme le fichier CSV en JSON
    events:
      - schedule:
          rate: "14 0 * * *"

plugins:
  - serverless-scaleway-functions
  - serverless-python-requirements

custom:
  pythonRequirements:
    noDeploy:
      - csv
      - json
      - urllib
      - gzip
      - datetime

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"
    - "!.idea/**"
    - "!*.html"
    - "!*.md"
    - "!*.txt"
    - "!docs/**"
