service: stabilitywarrants
configValidationMode: off
frameworkVersion: '2 || 3'


provider:
  name: scaleway
  runtime: python3
  
functions:
  sort:
    handler: sort.handle
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule:
        rate: '0 21 * * MON-FRI *'
        
plugins:
  - serverless-scaleway-functions
